development: &default
  adapter: postgresql
  encoding: unicode
  database: dev
  pool: 5
  username: postgres
  password:
  host: db
  timeout: 5000

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod
